### ISSUE TITLE
Profile page text update header

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/snippets#130]
The Header is incorrect, it should be something like `My Profile` or `Profile`. And, the link redirected by the button `View Github` is redirecting to this url https://github.com/profile  and not the profile of the user.

![Image](https://github.com/user-attachments/assets/26be3a66-6b4e-4a8b-9a80-2f1210dbb365)

**Comment by SufyaanKhateeb** [comment]
I can work on this.

**Comment by imrishabh18** [comment]
We are not assigning issues, until you have decent contribution in this repository. But feel free to work on this and open a PR

**Comment by SufyaanKhateeb** [comment]
This issue seems to occur only if you navigate to the profile page using the footer link. This footer "My Profile" link is visible even if the user is not logged in, so what is the expected behaviour on clicking the link in that case or should I just hide the button in that case?

The footer link redirects you to the /profile if we just fix the redirect to go to the /{username} this problem will be fixed and also in this case the header text will be {username}'s profile, do you want it to be "My profile" or "Profile" if the user is in their profile page?

**Comment by imrishabh18** [comment]
The profile link should not be visible in the footer when the user is not logged in.

cc: @seveibar

**Comment by SufyaanKhateeb** [comment]
@imrishabh18 or @seveibar Can you please add the hacktoberfest-accepted label to this issue.

**Comment by imrishabh18** [comment]
@SufyaanKhateeb Not needed, this repository has the `hacktoberfest` label. When you PR gets merged it will be counted towards the Hacktoberfest

**Comment by SufyaanKhateeb** [comment]
It has been merged BTW. You can close this issue if it is OK.
