### ISSUE TITLE
Manual edits file doesn't save/persist, doesn't work on View Snippets page

### ISSUE THREAD

**Issue by seveibar** [tscircuit/snippets#221]
CC @imrishabh18 can give more details

/bounty $40

**Comment by hunxjunedo** [comment]
@imrishabh18 I'd like to work on this, can you please share instructions to reproduce this ?

**Comment by imrishabh18** [comment]
- @hunxjunedo For this issue, as you can see in the video, that in the _view  snippets page_, in the files `manula-edits.json` is not there and because of that when you move components or edit traces it is not persisted. While the edit code page is having the persistance (currently there is some bug and even there the persistence is not working)

  [https://github.com/user-attachments/assets/9dfa7aa4-be21-466a-b9dc-a2bcfdc08993](https://github.com/user-attachments/assets/9dfa7aa4-be21-466a-b9dc-a2bcfdc08993)

**Comment by hunxjunedo** [comment]
@imrishabh18 so I've successfully investigated looked into it, there are a few things I want discuss before writing the solution, can we have a call ?

**Comment by imrishabh18** [comment]
@hunxjunedo Please join our discord, and paste your questions there. We can have a discussion over there
