### ISSUE TITLE
Make playwright tests not flaky

### ISSUE THREAD

**Issue by seveibar** [tscircuit/snippets#346]
I keep seeing broken playwright tests in PRs

I don't know why it's flaky, but we shouldn't be seeing that so often in PRs

/bounty $5

**Comment by seveibar** [comment]
Yes if its idiomatic

**Comment by Anshgrover23** [comment]
@seveibar the tests are flaky they somtime passed but sometimes they take more time due to UI Delays
Before:
![Image](https://github.com/user-attachments/assets/b0ce14c1-8798-403d-a180-056d4faf76b5)
After tracing each of them:
- Some failed due to timeouts because some tests are accesing more than 1 UI elements and due to this they are fail to do in required time.
![Image](https://github.com/user-attachments/assets/6c6ad3f6-4c26-463e-903d-955262a301c8)
![Image](https://github.com/user-attachments/assets/9c2d1006-da53-43db-80ac-08f2a7557317)
![Image](https://github.com/user-attachments/assets/3459cc50-b164-44a7-bf38-7c8265d2f38d)
